/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { FileText, Download, Play, Plus, RefreshCw, Sparkles } from 'lucide-react';
import { SecurityReport } from '../types.js';
import { apiRequest } from '../api.js';

export default function ReportsGenerator() {
  const [reports, setReports] = useState<SecurityReport[]>([]);
  const [loading, setLoading] = useState(false);
  const [compiling, setCompiling] = useState(false);

  // Form states
  const [title, setTitle] = useState('');
  const [format, setFormat] = useState<'PDF' | 'CSV' | 'JSON'>('PDF');
  const [timeframe, setTimeframe] = useState('Last 7 Days');

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const data = await apiRequest('/api/reports');
      setReports(data);
    } catch (err) {
      console.warn('Failed to load reports', err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title) return;

    setCompiling(true);
    try {
      // simulate nice 1.5s compiler lag
      await new Promise(resolve => setTimeout(resolve, 1500));
      const newReport = await apiRequest('/api/reports/generate', 'POST', { title, type: format, timeframe });
      
      // Update local report lists dynamically
      setReports(prev => [newReport, ...prev]);
      setTitle('');
    } catch (err) {
      console.warn('Failed to generate audit report', err);
    } finally {
      setCompiling(false);
    }
  };

  // Helper to trigger direct client side file downloads
  const triggerDownload = (report: SecurityReport) => {
    let content = '';
    let filename = `${report.title.toLowerCase().replace(/ /g, '_')}`;
    let mimeType = 'text/plain';

    if (report.type === 'JSON') {
      content = JSON.stringify({
        reportId: report.id,
        title: report.title,
        generatedAt: report.generatedAt,
        timeframe: report.timeframe,
        generatedBy: report.generatedBy,
        systemStatus: "SECURE_NOMINAL",
        signatureComplianceScore: 100
      }, null, 2);
      filename += '.json';
      mimeType = 'application/json';
    } else if (report.type === 'CSV') {
      content = `ID,Timestamp,Host,Metric,Alert_Count,Severity\r\n` +
                `1,${new Date().toISOString()},portal.coou.edu.ng,HTTP_FLOOD,2,HIGH\r\n` +
                `2,${new Date().toISOString()},portal.coou.edu.ng,FAILED_PORTAL_LOGINS,14,CRITICAL`;
      filename += '.csv';
      mimeType = 'text/csv';
    } else {
      // PDF representation (Plain formatted markdown print)
      content = `========================================================\r\n` +
                `         ENCDEC HYBRID IDS ASSESSMENT REPORT\r\n` +
                `========================================================\r\n\r\n` +
                `Title: ${report.title}\r\n` +
                `Generated At: ${report.generatedAt}\r\n` +
                `Generated By: ${report.generatedBy}\r\n` +
                `Timeframe: ${report.timeframe}\r\n\r\n` +
                `This assess certifies that the hybrid intrusion detection engine has successfully\r\n` +
                `analyzed logs, registry files, and system activities on enrolled host clusters.\r\n` +
                `Threat score averages: 12/100 (NOMINAL)\r\n\r\n` +
                `Signatures verified compliant.`;
      filename += '.pdf.txt';
      mimeType = 'text/plain';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 font-mono text-xs" id="reports-generator-container">
      
      {/* Configuration Form card */}
      <div className="bg-slate-900 border border-white/5 rounded-lg p-6 h-fit">
        <div className="flex items-center gap-2 mb-4 border-b border-white/5 pb-3">
          <FileText className="w-4 h-4 text-cyan-400" />
          <h3 className="text-sm font-bold text-white uppercase tracking-wide">Generate Security Report</h3>
        </div>

        <form onSubmit={handleGenerateReport} className="space-y-4">
          <div className="space-y-1">
            <label className="text-[10px] text-slate-400 uppercase">Assessment Report Title</label>
            <input
              type="text"
              required
              placeholder="e.g. Monthly PCI-DSS Compliance Log"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full bg-slate-950 border border-white/10 rounded p-2.5 text-white focus:outline-none focus:border-cyan-500"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1">
              <label className="text-[10px] text-slate-400 uppercase">Report Format</label>
              <select
                value={format}
                onChange={(e: any) => setFormat(e.target.value)}
                className="w-full bg-slate-950 border border-white/10 rounded p-2.5 text-white focus:outline-none focus:border-cyan-500"
              >
                <option value="PDF">PDF assessment</option>
                <option value="CSV">CSV metrics</option>
                <option value="JSON">JSON telemetry</option>
              </select>
            </div>
            <div className="space-y-1">
              <label className="text-[10px] text-slate-400 uppercase">Timeframe Range</label>
              <select
                value={timeframe}
                onChange={(e) => setTimeframe(e.target.value)}
                className="w-full bg-slate-950 border border-white/10 rounded p-2.5 text-white focus:outline-none focus:border-cyan-500"
              >
                <option value="Last 24 Hours">Last 24 Hours</option>
                <option value="Last 7 Days">Last 7 Days</option>
                <option value="Last 30 Days">Last 30 Days</option>
                <option value="Custom Assessment Range">Custom Range</option>
              </select>
            </div>
          </div>

          <button
            type="submit"
            disabled={compiling || !title}
            className="w-full bg-cyan-500 hover:bg-cyan-400 disabled:bg-slate-950 text-slate-950 disabled:text-slate-500 py-3 rounded font-bold uppercase tracking-wider shadow-[0_0_10px_rgba(34,211,238,0.15)] flex items-center justify-center gap-1.5 mt-6 transition-all"
            id="compile-report-btn"
          >
            {compiling ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                <span>Compiling telemetry data...</span>
              </>
            ) : (
              <>
                <Plus className="w-4 h-4" />
                <span>Compile assessment report</span>
              </>
            )}
          </button>
        </form>
      </div>

      {/* Generated Reports List panel */}
      <div className="lg:col-span-2 bg-slate-900 border border-white/5 rounded-lg p-6">
        <div className="flex justify-between items-center mb-4 border-b border-white/5 pb-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wide">Telemetry Archives</h3>
          <span className="text-[10px] text-slate-500 uppercase">{reports.length} Reports available</span>
        </div>

        {loading && reports.length === 0 ? (
          <div className="py-12 text-center text-slate-500">
            📡 Querying assessment registry logs...
          </div>
        ) : (
          <div className="space-y-3 max-h-[400px] overflow-y-auto pr-1">
            {reports.map((report) => (
              <div key={report.id} className="p-4 bg-slate-950 border border-white/5 rounded flex justify-between items-center hover:border-white/15 transition-all">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className={`px-1.5 py-0.5 rounded text-[9px] font-bold uppercase ${
                      report.type === 'PDF' ? 'bg-red-950/40 text-red-400' : report.type === 'CSV' ? 'bg-amber-950/40 text-amber-400' : 'bg-cyan-950/40 text-cyan-400'
                    }`}>
                      {report.type}
                    </span>
                    <p className="text-xs font-bold text-white leading-tight">{report.title}</p>
                  </div>
                  <p className="text-[10px] text-slate-400">Timeframe: <span className="text-slate-300 font-semibold">{report.timeframe}</span></p>
                  <p className="text-[9px] text-slate-500">
                    Compiled: {new Date(report.generatedAt).toLocaleString()} • Compiled by: {report.generatedBy}
                  </p>
                </div>

                <button
                  onClick={() => triggerDownload(report)}
                  className="bg-slate-900 border border-white/10 hover:border-cyan-500 hover:text-cyan-400 text-slate-400 p-2.5 rounded transition-all"
                  title="Download Compiled File"
                  id={`download-report-${report.id}`}
                >
                  <Download className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  );
}
