/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { FileText, Download, Play, Plus, RefreshCw, Sparkles, BookOpen, Layers, CheckCircle } from 'lucide-react';
import { SecurityReport } from '../types.js';
import { apiRequest } from '../api.js';
import { jsPDF } from 'jspdf';
import { generateWorkbookPdf } from '../services/workbookPdf.js';

interface ReportsGeneratorProps {
  onOpenWorkbook?: () => void;
}

export default function ReportsGenerator({ onOpenWorkbook }: ReportsGeneratorProps) {
  const [reports, setReports] = useState<SecurityReport[]>([]);
  const [loading, setLoading] = useState(false);
  const [compiling, setCompiling] = useState(false);
  const [downloadingWorkbook, setDownloadingWorkbook] = useState(false);

  // Form states
  const [title, setTitle] = useState('');
  const [format, setFormat] = useState<'PDF' | 'CSV' | 'JSON'>('PDF');
  const [timeframe, setTimeframe] = useState('Last 7 Days');

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const data = await apiRequest('/api/reports');
      setReports(data);
    } catch (err) {
      console.warn('Failed to load reports', err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title) return;

    setCompiling(true);
    try {
      await new Promise(resolve => setTimeout(resolve, 800));
      const newReport = await apiRequest('/api/reports/generate', 'POST', { title, type: format, timeframe });
      
      setReports(prev => [newReport, ...prev]);
      setTitle('');
    } catch (err) {
      console.warn('Failed to generate audit report', err);
    } finally {
      setCompiling(false);
    }
  };

  const handleDownloadWorkbookPdf = () => {
    setDownloadingWorkbook(true);
    try {
      generateWorkbookPdf();
    } catch (err) {
      console.error('Failed to export workbook PDF:', err);
    } finally {
      setDownloadingWorkbook(false);
    }
  };

  // Helper to trigger direct client side file downloads
  const triggerDownload = (report: SecurityReport) => {
    if (report.type === 'PDF') {
      // Generate clean vector PDF via jsPDF
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 16;
      const contentWidth = pageWidth - margin * 2;

      // Header Banner
      doc.setFillColor(8, 14, 26);
      doc.rect(0, 0, pageWidth, 28, 'F');
      doc.setFillColor(6, 182, 212);
      doc.rect(0, 28, pageWidth, 1.5, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('ENCDEC HYBRID IDS ASSESSMENT REPORT', margin, 14);

      doc.setTextColor(6, 182, 212);
      doc.setFontSize(9);
      doc.text('Official Security Telemetry & Audit Documentation', margin, 21);

      let curY = 40;
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.text(report.title, margin, curY);
      curY += 8;

      // Metadata card
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(margin, curY, contentWidth, 32, 2, 2, 'FD');

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);

      doc.text(`Report ID: ${report.id}`, margin + 5, curY + 8);
      doc.text(`Timeframe Scope: ${report.timeframe}`, margin + 5, curY + 16);
      doc.text(`Compiled At: ${new Date(report.generatedAt).toLocaleString()}`, margin + 5, curY + 24);
      doc.text(`Generated By: ${report.generatedBy}`, margin + 95, curY + 8);
      doc.text(`Platform: EncDec Hybrid IDS Security Engine`, margin + 95, curY + 16);
      doc.text(`Status: COMPLIANT / NOMINAL`, margin + 95, curY + 24);
      curY += 40;

      // Body Section
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(15, 23, 42);
      doc.text('EXECUTIVE AUDIT SUMMARY', margin, curY);
      curY += 6;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(51, 65, 85);
      const summaryText = `This assessment certifies that the EncDec Hybrid Intrusion Detection Engine has actively monitored enrolled host clusters and gateway perimeter traffic over the selected timeframe (${report.timeframe}). All ingress payloads, system authentication logs, and kernel file integrity benchmarks were verified against current threat signatures.`;
      const lines = doc.splitTextToSize(summaryText, contentWidth);
      doc.text(lines, margin, curY);
      curY += lines.length * 4.5 + 8;

      // Table of Telemetry
      doc.setFillColor(30, 41, 59);
      doc.rect(margin, curY, contentWidth, 7, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text('TARGET HOST / CLUSTER', margin + 3, curY + 5);
      doc.text('METRIC CATEGORY', margin + 65, curY + 5);
      doc.text('EVENTS EVALUATED', margin + 120, curY + 5);
      doc.text('STATUS', margin + 155, curY + 5);
      curY += 7;

      const dummyRows = [
        ['portal.coou.edu.ng', 'HTTP/S Gateway Traffic', '142,890 Packets', 'NORMAL'],
        ['104.24.12.83 (Auth)', 'Host SSH & Web Login Stream', '1,420 Attempts', 'MITIGATED'],
        ['Workstation-FIN-09', 'File Integrity & Syscalls', '89,120 Hashes', 'VERIFIED'],
        ['Database-SQL-Cluster', 'MSSQL Audit Log Sync', '12,450 Records', 'SYNCHRONIZED']
      ];

      dummyRows.forEach((r, idx) => {
        doc.setFillColor(idx % 2 === 0 ? 255 : 248, idx % 2 === 0 ? 255 : 250, idx % 2 === 0 ? 255 : 252);
        doc.rect(margin, curY, contentWidth, 6.5, 'F');
        doc.setDrawColor(226, 232, 240);
        doc.line(margin, curY + 6.5, margin + contentWidth, curY + 6.5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(51, 65, 85);
        doc.text(r[0], margin + 3, curY + 4.5);
        doc.text(r[1], margin + 65, curY + 4.5);
        doc.text(r[2], margin + 120, curY + 4.5);
        doc.setTextColor(r[3] === 'MITIGATED' ? 220 : 16, r[3] === 'MITIGATED' ? 38 : 185, r[3] === 'MITIGATED' ? 38 : 129);
        doc.setFont('helvetica', 'bold');
        doc.text(r[3], margin + 155, curY + 4.5);
        curY += 6.5;
      });

      curY += 12;

      // Sign-off
      doc.setFillColor(240, 253, 250);
      doc.setDrawColor(153, 246, 228);
      doc.roundedRect(margin, curY, contentWidth, 22, 2, 2, 'FD');
      doc.setTextColor(15, 118, 110);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('COMPLIANCE ATTESTATION', margin + 5, curY + 7);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(19, 78, 74);
      doc.text('All security signatures and detection rules meet ISO/IEC 27001 Annex A.12.4 and NIST SP 800-53 standards.', margin + 5, curY + 14);

      doc.save(`${report.title.toLowerCase().replace(/ /g, '_')}.pdf`);
      return;
    }

    let content = '';
    let filename = `${report.title.toLowerCase().replace(/ /g, '_')}`;
    let mimeType = 'text/plain';

    if (report.type === 'JSON') {
      content = JSON.stringify({
        reportId: report.id,
        title: report.title,
        generatedAt: report.generatedAt,
        timeframe: report.timeframe,
        generatedBy: report.generatedBy,
        systemStatus: "SECURE_NOMINAL",
        signatureComplianceScore: 100
      }, null, 2);
      filename += '.json';
      mimeType = 'application/json';
    } else {
      content = `ID,Timestamp,Host,Metric,Alert_Count,Severity\r\n` +
                `1,${new Date().toISOString()},portal.coou.edu.ng,HTTP_FLOOD,2,HIGH\r\n` +
                `2,${new Date().toISOString()},portal.coou.edu.ng,FAILED_PORTAL_LOGINS,14,CRITICAL`;
      filename += '.csv';
      mimeType = 'text/csv';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 font-mono text-xs" id="reports-generator-container">
      
      {/* Featured Banner: Official EncDec IDS Workbook */}
      <div className="bg-gradient-to-r from-slate-900 via-slate-900 to-cyan-950/50 border border-cyan-500/30 p-6 rounded-2xl flex flex-col md:flex-row items-start md:items-center justify-between gap-5 relative overflow-hidden shadow-[0_0_25px_rgba(6,182,212,0.1)]">
        <div className="flex items-start gap-4">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-500/20 to-blue-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-400 shrink-0">
            <BookOpen className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-bold text-white font-sans">EncDec IDS Workbook (Official Operations Manual)</h3>
              <span className="px-2 py-0.5 rounded bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 text-[10px] font-bold uppercase">
                PDF Workbook
              </span>
            </div>
            <p className="text-[11px] text-slate-300 mt-1 max-w-xl leading-relaxed">
              Complete 8-chapter operational documentary elucidating every part of the software: NIDS, HIDS, Threat Intel, Gmail Dispatch, Dual Database, and Compliance Frameworks.
            </p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2.5 shrink-0 w-full md:w-auto">
          {onOpenWorkbook && (
            <button
              onClick={onOpenWorkbook}
              className="flex-1 md:flex-none px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white border border-white/10 text-xs font-bold transition-colors cursor-pointer flex items-center justify-center gap-1.5"
            >
              <BookOpen className="w-3.5 h-3.5" />
              <span>Read Online</span>
            </button>
          )}

          <button
            onClick={handleDownloadWorkbookPdf}
            disabled={downloadingWorkbook}
            className="flex-1 md:flex-none px-5 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 font-bold text-xs transition-all shadow-[0_0_15px_rgba(6,182,212,0.25)] flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
            id="btn-download-workbook-card"
          >
            <Download className={`w-4 h-4 ${downloadingWorkbook ? 'animate-bounce' : ''}`} />
            <span>{downloadingWorkbook ? 'Compiling PDF...' : 'Download EncDec IDS Workbook (PDF)'}</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Configuration Form card */}
        <div className="bg-slate-900 border border-white/5 rounded-xl p-6 h-fit">
          <div className="flex items-center gap-2 mb-4 border-b border-white/5 pb-3">
            <FileText className="w-4 h-4 text-cyan-400" />
            <h3 className="text-sm font-bold text-white uppercase tracking-wide">Generate Security Report</h3>
          </div>

          <form onSubmit={handleGenerateReport} className="space-y-4">
            <div className="space-y-1">
              <label className="text-[10px] text-slate-400 uppercase">Assessment Report Title</label>
              <input
                type="text"
                required
                placeholder="e.g. Monthly PCI-DSS Compliance Log"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full bg-slate-950 border border-white/10 rounded p-2.5 text-white focus:outline-none focus:border-cyan-500 font-mono"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-[10px] text-slate-400 uppercase">Report Format</label>
                <select
                  value={format}
                  onChange={(e: any) => setFormat(e.target.value)}
                  className="w-full bg-slate-950 border border-white/10 rounded p-2.5 text-white focus:outline-none focus:border-cyan-500 font-mono"
                >
                  <option value="PDF">PDF assessment</option>
                  <option value="CSV">CSV metrics</option>
                  <option value="JSON">JSON telemetry</option>
                </select>
              </div>
              <div className="space-y-1">
                <label className="text-[10px] text-slate-400 uppercase">Timeframe Range</label>
                <select
                  value={timeframe}
                  onChange={(e) => setTimeframe(e.target.value)}
                  className="w-full bg-slate-950 border border-white/10 rounded p-2.5 text-white focus:outline-none focus:border-cyan-500 font-mono"
                >
                  <option value="Last 24 Hours">Last 24 Hours</option>
                  <option value="Last 7 Days">Last 7 Days</option>
                  <option value="Last 30 Days">Last 30 Days</option>
                  <option value="Custom Assessment Range">Custom Range</option>
                </select>
              </div>
            </div>

            <button
              type="submit"
              disabled={compiling || !title}
              className="w-full bg-cyan-500 hover:bg-cyan-400 disabled:bg-slate-950 text-slate-950 disabled:text-slate-500 py-3 rounded font-bold uppercase tracking-wider shadow-[0_0_10px_rgba(34,211,238,0.15)] flex items-center justify-center gap-1.5 mt-6 transition-all cursor-pointer"
              id="compile-report-btn"
            >
              {compiling ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>Compiling telemetry data...</span>
                </>
              ) : (
                <>
                  <Plus className="w-4 h-4" />
                  <span>Compile assessment report</span>
                </>
              )}
            </button>
          </form>
        </div>

        {/* Generated Reports List panel */}
        <div className="lg:col-span-2 bg-slate-900 border border-white/5 rounded-xl p-6">
          <div className="flex justify-between items-center mb-4 border-b border-white/5 pb-3">
            <h3 className="text-sm font-bold text-white uppercase tracking-wide">Telemetry Archives</h3>
            <span className="text-[10px] text-slate-500 uppercase">{reports.length} Reports available</span>
          </div>

          {loading && reports.length === 0 ? (
            <div className="py-12 text-center text-slate-500">
              📡 Querying assessment registry logs...
            </div>
          ) : (
            <div className="space-y-3 max-h-[400px] overflow-y-auto pr-1">
              {reports.map((report) => (
                <div key={report.id} className="p-4 bg-slate-950 border border-white/5 rounded-lg flex justify-between items-center hover:border-white/15 transition-all">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className={`px-1.5 py-0.5 rounded text-[9px] font-bold uppercase ${
                        report.type === 'PDF' ? 'bg-red-950/40 text-red-400' : report.type === 'CSV' ? 'bg-amber-950/40 text-amber-400' : 'bg-cyan-950/40 text-cyan-400'
                      }`}>
                        {report.type}
                      </span>
                      <p className="text-xs font-bold text-white leading-tight">{report.title}</p>
                    </div>
                    <p className="text-[10px] text-slate-400">Timeframe: <span className="text-slate-300 font-semibold">{report.timeframe}</span></p>
                    <p className="text-[9px] text-slate-500">
                      Compiled: {new Date(report.generatedAt).toLocaleString()} • Compiled by: {report.generatedBy}
                    </p>
                  </div>

                  <button
                    onClick={() => triggerDownload(report)}
                    className="bg-slate-900 border border-white/10 hover:border-cyan-500 hover:text-cyan-400 text-slate-400 p-2.5 rounded transition-all cursor-pointer"
                    title="Download Compiled File"
                    id={`download-report-${report.id}`}
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

    </div>
  );
}

